### ISSUE TITLE
Cannot train chatbot / An error ocurred in NLU Server

### ISSUE THREAD

**Issue by pedrofnts** [botpress/v12#1759]
**Describe the bug**
I'm trying to train a chatbot in Portuguese.

Everytime I click "Train chatbot", the button reloads and nothing happens.

On logs, there is:

```
An error occured when training [Error, An error occured in NLU server: child "intents" fails because ["intents" at position 0 fails because [child "utterances" fails because ["utterances" is required]]]]
STACK TRACE
Error: An error occured in NLU server: child "intents" fails because ["intents" at position 0 fails because [child "utterances" fails because ["utterances" is required]]]
    at NLUClient._throwError (/botpress/modules/.cache/module__a0c1c3e4de8832e0915fa84c8fa94151edcc03521e2be51b86e69af2510e8f85/dist/backend/application/nlu-client/index.js:133:11)
    at NLUClient.startTraining (/botpress/modules/.cache/module__a0c1c3e4de8832e0915fa84c8fa94151edcc03521e2be51b86e69af2510e8f85/dist/backend/application/nlu-client/index.js:82:19)
    at async BotState.startTraining (/botpress/modules/.cache/module__a0c1c3e4de8832e0915fa84c8fa94151edcc03521e2be51b86e69af2510e8f85/dist/backend/application/bot/bot-state.js:33:23)
    at async Trainer.train (/botpress/modules/.cache/module__a0c1c3e4de8832e0915fa84c8fa94151edcc03521e2be51b86e69af2510e8f85/dist/backend/application/bot/trainer.js:41:9)
```

How to solve that?

**To Reproduce**

Training a chatbot with intents in portuguese.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- NodeJS: 18.17.0

**Comment by Mikhail84** [comment]
I couldn't start train process too. I tried to find problem and seen that language server docker container not up, and fails every time i restart it. So, i had update docker image, create new containers with new version of Botpress (12.30.10). Now Botpress training ok
