### ISSUE TITLE
BOTPRESS responding in emulator but not in Webchat

### ISSUE THREAD

**Issue by m00ali** [botpress/v12#1807]
the error I am facing is :

```
Jan 31, 2024, 6:12:12 PM
error in handler fe [Error]: An unexpected error occurred when trying to process your request. (Error ID: err_20240131131212xD1CA6C84)
    at Bc (/var/task/customer_code.js:11:62529)
    at Nt (/var/task/customer_code.js:11:62351)
    at R (/var/task/customer_code.js:11:71961)
    at /var/task/customer_code.js:11:64049
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onTrigger (/var/task/customer_code.js:649:9675)
    at async handler (/var/task/customer_code.js:1732:7785)
    at async /var/task/index.js:20:13702
    at async handleHTTPEvent (/var/task/index.js:20:13678)
    at async Runtime.handler (/var/task/index.js:20:13567) {
  isApiError: true,
  code: 500,
  description: 'An unknown error occurred',
  type: 'Unknown',
  error: undefined,
  id: 'err_20240131131212xD1CA6C84'
}
Timestamp
Jan 31, 2024, 6:12:12 PM
Level
ERROR
```
I have checked on both windows10 and windows11. The bot is simple drag and drop with minimal js used in webhooks . Nothing else. it was working properly but now it doesn't respond on website where I have done it live.

![image](https://github.com/botpress/v12/assets/139992020/1cfcbed6-b75c-4d45-96eb-9350243c5498)

**Comment by sebburon** [comment]
I'm not sure this is a product bug. You can head to the v12 channel in our discord and get some help resolving this.
discord.gg/botpress
